name: Trionix-LAB Documentation site
description: Trionix-LAB Documentation site

logo: /documentation/logo_nav.png
title: docs.trionix-lab.ru
email: info@trionix-lab.ru
description: >
  Trionix-LAB site for
  products documentation
baseurl: "" 
url: "http://docs.trionix-lab.ru"
github_username:  trionix-lab

# show_downloads: false

remote_theme: "jekyll/minima@1e8a445"
plugins:
- jekyll-remote-theme 

disqus: